name: Artifacts
version: '1.0-Earnings'
main: org.akorpuzz.artifacts.Artifacts
api-version: '1.21'
softdepend:
  - Vault
commands:
  artifactsearnings:
    description: Abre el menu de artefactos
    usage: /<command>
